### ISSUE TITLE
FAQ page hifi 

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#175]
Please work on hifi for the FAQ page.

**Comment by kashikushi** [comment]
@ma2b0043 
The FAQ page has been ready to hand off to the FE team. 
Here is the Figma link: 
https://www.figma.com/file/C22D4Et2I0AIE0n8QwBDMm/FAQ?node-id=152%3A3508
Here is the FAQ content link:
https://docs.google.com/document/d/12DzwJnge7LaVabgtnkIjM9fpuVp1fNS4KdVsndiU4uc/edit?usp=sharing
