### ISSUE TITLE
Project Rules & Guidelines - Update UI with new style

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#191]
1. Review all the different sections we have for the Project overview, rules, guidelines, process, etc. Please go through the process of submitting a project yourself and see how we can make this more understandable for people to start submitting projects.
2. If you think the pages can be chunked out differently, please feel free to pitch those too. All the information on the website is all finalized content, so we can now play around with how to make it more understandable to users. 
3. We need to make all the information more easily understandable by adding visuals as well. Would be more interesting than just seeing chunks of text as well.

**Comment by kashikushi** [comment]
Existing rules and guide page
https://thenewboston.com/projects/overview

**Comment by kashikushi** [comment]
Handoff
https://www.figma.com/file/ei4V944GJrWz78Kyr7IW9f/Project-Rules-and-Guidelines?node-id=379%3A4455
