### ISSUE TITLE
Make a design for "Milestone for team page"

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Design-Only#192]
You need to make a design to "Milestone for team page" as mentioned by @buckyroberts in [140](https://github.com/thenewboston-developers/Management/issues/140). Once you are done with this, kindly send me the figma link, so that I can share that with FE team and if they are all satisfied, then we can close this issue.

If you any issue, kindly contact me on discord.

**Comment by ma2b0043** [comment]
@kristykjlee whats the status of this issue?

**Comment by kristykjlee** [comment]
@ma2b0043 Ready to handoff to engineering.

**Comment by ma2b0043** [comment]
> @ma2b0043 Ready to handoff to engineering.

Kristy can you send me a figma link this design? so that I can pass that on the FE

**Comment by kristykjlee** [comment]
@ma2b0043 https://www.figma.com/file/tetFi2AzrcvNpS8mTUNtkM/Weekly-Progress?node-id=0%3A1
