### ISSUE TITLE
Make a design for adding Terms of Use and Privacy Policy to the website

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Design-Only#195]
You need make a design for the "Terms of Use" and "Privacy Policy", to be added onto the website. Kindly tell me, where do you think it will best fit on the website, I recommend that we make a separate page for this, on the website but what do you think. You can get the docs from this issue "[146](https://github.com/thenewboston-developers/Management/issues/146)".

 If you dont have access to those documents, kindly let me know.

**Comment by kristykjlee** [comment]
@ma2b0043 Done 
https://www.figma.com/file/jtTuZ9iGLMiza4yoNAQdV7/Terms-of-Use-and-Privacy-Policy?node-id=0%3A1

**Comment by kristykjlee** [comment]
@ma2b0043 Ready to handoff to engineering.

**Comment by ma2b0043** [comment]
> @ma2b0043 Ready to handoff to engineering.

Kristy we talked about this issue on discord, so we should let it stay as it is, for now.

**Comment by kristykjlee** [comment]
> > @ma2b0043 Ready to handoff to engineering.
> 
> Kristy we talked about this issue on discord, so we should let it stay as it is, for now.

Yes, sounds good
