### ISSUE TITLE
Newsletter page

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design-Only#197]
Page on the website where users can download the newsletters. Also if they miss an announcement then they can always just check there.

**Comment by ma2b0043** [comment]
should I assign somebody to this?

**Comment by kashikushi** [comment]
Here is HiFi responsive newsletter.
https://www.figma.com/file/zHkdKxSOz1LzAfT0Intoyq/Newsletters?node-id=92%3A1509

**Comment by AnasNadeem** [comment]
Well i want to do this. Will you assign me please?

**Comment by ma2b0043** [comment]
> Well i want to do this. Will you assign me please?

Anas, this is a core team task, meaning only core team members can complete this. If you want to contribute to the network you can either complete a "bounty" labeled task or submit a project proposal for some exciting idea that will add value to our network. For further information, you can contact me on discord(username: Muhammad Anas Azam Bhatti#3383).
