### ISSUE TITLE
Developer tools page

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design-Only#198]
We will be creating a developer tools page based on Tomis suggestion for our libraries, SDKs, etc... 

@led76marx could you write up the requirements that we need to hand off to design? We don't have any details other than what Tomi suggested so whatever we want to put on there is up to you.

**Original suggestion from Tomi:**
> For the website we could have a developer tools page that showcases all the GitHub repo's and payment libraries that will be useful for projects. Something like https://nano.org/tools.

**Comment by led76marx** [comment]
Closing this, since we have an doc outlining our dev portal strategy. Kicking this off asap.
