### ISSUE TITLE
Improve UX for application process

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design-Only#205]
Bojan left this comment in the #marketing channel in Discord.

<img width="745" alt="Screen Shot 2021-04-29 at 4 16 07 PM" src="https://user-images.githubusercontent.com/8547538/116629559-566fd680-a906-11eb-8682-d76c54676058.png">

**Comment by kristykjlee** [comment]
@buckyroberts  This one has been resolved. The issue with the previous process was mid-way through the form, we asked the user to download the app and give us their account # which seemed strange esp to new users, so that is no longer a requirement.
