### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design-Only#209]
We would like to have an area on the website where we can view various analytics. These include stats from social media, website analytics, network stats, etc...

It will include the analytics and charts on this page, plus some additional ones as well. @Chrisha1212 is gathering up all the stats we will need to track now so we will update this GitHub issue with a full list soon.

https://docs.google.com/spreadsheets/d/1azVOKoVohWpR3_DL64h8_G3Aho8K8usMmUJq0HPteBs/edit?usp=sharing

We will be using this charting library so please use it in the mocks - https://recharts.org/en-US/examples

**Comment by angle943** [comment]
https://recharts.org/en-US/api

**Comment by Chrisha1212** [comment]
**Twitter**- https://docs.google.com/spreadsheets/d/1QaO2Tql7n6o0fpOFtE571BZjGJTXc6a3TVuifjZq_MQ/edit#gid=0
**Facebook-** https://docs.google.com/spreadsheets/u/1/d/1A50NBAp-4JnX2kHRhbWkivE7YXgC9SGcWbzHl3kcK78/edit?usp=drive_web&ouid=104574473735060237502 
**Instagram**- https://docs.google.com/spreadsheets/d/1sAcuNi29lnCMNluutSDkBSfjyrT55Qmez1OneFnQI-Y/edit#gid=0
**LinkedIn**- https://docs.google.com/spreadsheets/d/1nJKKD9WN2sybQNotAuvPGefd0AgG8rOO84CvRnYtQKc/edit#gid=0
**Daily Coins Release**- https://docs.google.com/spreadsheets/d/1UhBjzRPQP6L9ZZy_1zb7cpEoK2XzfunfsVCeWzGpdJQ/edit#gid=0
**Summary**- https://docs.google.com/spreadsheets/d/1azVOKoVohWpR3_DL64h8_G3Aho8K8usMmUJq0HPteBs/edit#gid=0

**Comment by kashikushi** [comment]
### Proof of Work
- https://www.figma.com/file/wWisZsaUf9xzkCCqlzvG3G/Analytics?node-id=1%3A4
- https://www.figma.com/file/wWisZsaUf9xzkCCqlzvG3G/Analytics?node-id=243%3A0

**Comment by ma2b0043** [comment]
> ### Proof of Work
> * https://www.figma.com/file/wWisZsaUf9xzkCCqlzvG3G/Analytics?node-id=1%3A4
> * https://www.figma.com/file/wWisZsaUf9xzkCCqlzvG3G/Analytics?node-id=243%3A0

Mr K, I dont have access to these files.
