### ISSUE TITLE
Design Developer Portal's Landing Page

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Design-Only#210]
Hi, you need to design the landing page for the "Developer Portal". 

I'm compiling a list of ideas for the landing page as well, which are added in this doc: https://docs.google.com/document/d/1X9tX9EjA0ZQU9jQq3RceXJRyYcmvk6YLfrioqLL_2p8/edit?usp=sharing

We can discuss this in detail in the weekly developer portal meeting.

**Comment by kashikushi** [comment]
https://docs.google.com/document/d/1Y9d6FQb3jvcshPXWwvBD8Y_y1v2_iYnBZRUSR4-Plnw/edit#heading=h.yiytubs708o3

**Comment by kashikushi** [comment]
UI & Handoff Figma File link for Dev. Portal Landing page
https://www.figma.com/file/PRQm1ArLsBy1aZh2rZFwDz/Developer-Portal-s-Landing-Page?node-id=625%3A0

**Comment by buckyroberts** [comment]
@kristykjlee I will write up the FE tickets for this
