### ISSUE TITLE
Beta Roadmap

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design-Only#219]
**Task**
Design beta roadmap for website. 

**Why**
Core team and community members would like to have better insight into what tasks need to be accomplished in order to reach beta and also estimated completion dates for both individual tasks and the overall network.

![Beta Roadmap](https://user-images.githubusercontent.com/8547538/120560630-e4ccf180-c3b7-11eb-8560-eb119bb7e2af.png)

**Comment by kristykjlee** [comment]
Quick Update: After talking with Bucky, we are not going tobe including Points for the roadmap. Everything else will remain.

**Comment by kashikushi** [comment]
HiFi UI Design
https://www.figma.com/file/0Mbdp8cBqu4P4h7pwLzowI/Beta-Roadmap?node-id=2%3A20
