### ISSUE TITLE
App Store

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design-Only#222]
**Required**
- Logo (for list view)
- App name
- Short description (for list view)
- Long description (for detail view) - markdown
- Minimum of 2 screenshots for detail page carousel

**Optional**
- Link to website
- Documentation
- Video

**Notes**
- For the mobile app we can include a link on the download page (incase they are looking on that page)
- Do we need a privacy policy?

**Future / Post MVP**
- Reviews
- Download count

https://www.figma.com/file/zbQ5xuZqAfhAlOiy9ilZlm/App-Store?node-id=0%3A1

**Comment by kashikushi** [comment]
HiFi UI Design file
https://www.figma.com/file/zbQ5xuZqAfhAlOiy9ilZlm/App-Store?node-id=181%3A4331

**Comment by kashikushi** [comment]
Handoff ready for new UI design
https://www.figma.com/file/zbQ5xuZqAfhAlOiy9ilZlm/App-Store?node-id=771%3A7525
