### ISSUE TITLE
Living Whitepaper

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#223]

**Comment by kashikushi** [comment]
Content:
https://docs.google.com/document/d/1_6OCmqL0OK5UiWJROe-EbRYAQa9s-iuIIQOdv_Vd5Bs/edit
UI & Handoff
https://www.figma.com/file/x6gQN0dfrzCq1iDfbLQTXZ/Living-Whitepaper?node-id=1%3A3

**Comment by kashikushi** [comment]
https://drive.google.com/drive/folders/1WZYNsT2bJ16_zbteY34gd2HHfIPeyZUr?usp=sharing
[White Paper Diagrams-20210705T032731Z-001.zip](https://github.com/thenewboston-developers/Design/files/6762500/White.Paper.Diagrams-20210705T032731Z-001.zip)
