### ISSUE TITLE
Handoff for Terms of Use & Privacy Policy

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#226]
I updated all the information on the Terms of Use & Privacy Policy mocks itself. @kashikushi Can you create the handoff for this UI please? Information on the UI page is all accurate, just needs handoff.
https://www.figma.com/file/jtTuZ9iGLMiza4yoNAQdV7/Terms-of-Use-and-Privacy-Policy?node-id=0%3A1

**Comment by kashikushi** [comment]
ok. I'll work on Handoff and will let you know when completed.
