### ISSUE TITLE
SDK/Libraries

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#228]
Skip down to the SDK/Libraries section and you can view what the content is for the SDK/Libraries page. 
https://docs.google.com/document/d/1BTyu2jh2OtNU5sZorSic3zAtGesahzizSotqFZPf_wc/edit

**Comment by kashikushi** [comment]
UI Design file
https://www.figma.com/file/6NA1usM50PE2DG74CjL8A5/SDK-Libraries?node-id=189%3A1969
