### ISSUE TITLE
Project FAQ Update

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Design-Only#229]
We need to update the project page. Please add these updates to the project page design.

**Updated Content:** https://docs.google.com/document/d/1KTn4Zm3YgyIqremjB232gHZjPAbwXJEjRLukFEoDOIQ/edit#heading=h.3nqhmts7mcen

**Design to be updated:** 
https://www.figma.com/file/5madc2zFyUi7A3G0ZeFcry/Integrated-Projects-%26-Rules?node-id=0%3A1

---

**Task:** Make the `Project FAQ` section to the bottom of the page

**Comment by kashikushi** [comment]
Updated RULES & GUIDELINES page with FAQ
https://www.figma.com/file/5madc2zFyUi7A3G0ZeFcry/Integrated-Projects-and-Rules?node-id=382%3A7693
