### ISSUE TITLE
Design Featured Images for Apps

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#239]
Design awesome featured images for these apps:
1. [Keysign](https://developer.thenewboston.com/projects/approved-projects/00e64bb4-37b0-453e-a778-26251818affc)
2. [TNB Faucet](https://developer.thenewboston.com/projects/approved-projects/589649fb-dfaa-4081-b04a-2e9179cf1a21)
3. [TNB Discord Bot](https://developer.thenewboston.com/projects/approved-projects/42d288db-862c-4920-be4b-56f53445b58d)
4. [HD Keygen](https://developer.thenewboston.com/projects/approved-projects/2058c70b-c5f2-404b-a377-ab767937b651)
5. [TNB Discord Shop](https://developer.thenewboston.com/projects/approved-projects/cc5c6721-a8d3-4a5d-913f-facd3fd476d0)
6. [TNBC Games](https://tnbcgames.com/)
7. [CodeArkive](https://codearkive.pythonanywhere.com/)

**Graphics should be of 1:1 ratio** (280px X 280px)

**Here are few examples:**
![Screen Shot 2021-09-27 at 12 44 36 PM](https://user-images.githubusercontent.com/68207101/134974870-a8a056e2-db32-43ec-8396-f42222a415dc.png)

**Comment by Docebo-Netflix** [comment]
Here are the first few designs for the Featured Images for Apps

TNB Faucet
![TNB-App-Icons--TNB-Faucet](https://user-images.githubusercontent.com/78985665/135139931-5bce81a1-5894-4f49-bcf2-330db4df2dee.png)

Discord Bot
![TNB-App-Icons--Discord-Bot](https://user-images.githubusercontent.com/78985665/135139955-bf8dc09c-cd1b-4cad-ab37-6b485d995117.png)

Discord Store
![TNB-App-Icons-Discord-Store](https://user-images.githubusercontent.com/78985665/135139964-c3f291ce-b61d-406d-91b3-10a2dfdfbec6.png)

**Comment by Docebo-Netflix** [comment]
Here are more.

Code Arkive
![TNB-App-Icons-Code-Arkive](https://user-images.githubusercontent.com/78985665/135353656-c709fa8d-d695-4e55-9735-807d1900d71a.png)

HD Wallet
![TNB-App-Icons-HD-Wallet](https://user-images.githubusercontent.com/78985665/135353657-cec67f44-d12a-4398-a238-22ec0e7339d8.png)

TNB Games
![TNB-App-Icons-TNB-Games](https://user-images.githubusercontent.com/78985665/135353659-bbafd51b-f48e-42e3-978f-f61a1d4ca3b2.png)
..

**Comment by Docebo-Netflix** [comment]
![TNB-App-Icons-Keysign](https://user-images.githubusercontent.com/78985665/135588341-9aa205d1-a186-421d-a611-c6f5ade6ad56.png)
