### ISSUE TITLE
Design Featured Images for Apps

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#240]
Design awesome featured images for these apps:
1. [Keysign](https://developer.thenewboston.com/projects/approved-projects/00e64bb4-37b0-453e-a778-26251818affc)
2. [TNB Faucet](https://developer.thenewboston.com/projects/approved-projects/589649fb-dfaa-4081-b04a-2e9179cf1a21)
3. [TNB Discord Bot](https://developer.thenewboston.com/projects/approved-projects/42d288db-862c-4920-be4b-56f53445b58d)
4. [HD Keygen](https://developer.thenewboston.com/projects/approved-projects/2058c70b-c5f2-404b-a377-ab767937b651)
5. [TNB Discord Shop](https://developer.thenewboston.com/projects/approved-projects/cc5c6721-a8d3-4a5d-913f-facd3fd476d0)
6. [TNBC Games](https://tnbcgames.com/)
7. [CodeArkive](https://codearkive.pythonanywhere.com/)

**Graphics should be of 1:1 ratio** (280px X 280px)
No need to round out corners, just need to make it square.  

**Here are few examples:**
![Screen Shot 2021-09-27 at 12 44 36 PM](https://user-images.githubusercontent.com/68207101/134974870-a8a056e2-db32-43ec-8396-f42222a415dc.png)

**Comment by Toledit** [comment]
![collection](https://user-images.githubusercontent.com/27518021/135336735-0684895d-52bb-41b8-b1bf-8a50075d426b.jpg)

![featuredArtboard 1 copy 2](https://user-images.githubusercontent.com/27518021/135336392-5721bbf4-947c-4ee6-ab9e-3ac7b51caf3f.jpg)
![featuredArtboard 1 copy 3](https://user-images.githubusercontent.com/27518021/135336421-2a490655-ddbc-417f-a04c-126aa96097ba.jpg)
![featuredArtboard 1 copy 4](https://user-images.githubusercontent.com/27518021/135336435-e092ee45-4b8b-497d-8794-3887ec442c3a.jpg)
![featuredArtboard 1 copy 5](https://user-images.githubusercontent.com/27518021/135336451-17c6e6e4-ce28-4555-932f-b5cad84c145f.jpg)
![featuredArtboard 1 copy 6](https://user-images.githubusercontent.com/27518021/135336456-f5ec05ad-7de5-40d9-b21f-fc472eddddb0.jpg)
![featuredArtboard 1 copy](https://user-images.githubusercontent.com/27518021/135336458-feeea9f6-96ed-407f-bb4f-74bb8325fe1a.jpg)
![featuredArtboard 1](https://user-images.githubusercontent.com/27518021/135336462-c910a179-5711-4029-9ab7-14c3ac77fe0a.jpg)

**Comment by Toledit** [comment]
![TNBpay](https://user-images.githubusercontent.com/27518021/136710925-4f4532fd-086a-40ab-bd5b-64b4b9380b0d.png)
![Blockchain Explorer](https://user-images.githubusercontent.com/27518021/136710928-9120d037-e9e7-41b2-a844-2be525be5f0a.png)
