### ISSUE TITLE
App Screenshots

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#241]
Currently the apps in our App store do not have screenshots that display to the user of the app itself. https://thenewboston.com/arcade We need app screenshots for the apps listed below. The image needs to be 800x500. It will be ideal to have around 3-4 screenshots per app. 

Need app screenshots for:

1. CodeArkive
2. Blockchain Explorer
3. TNB Discord Bot
4. Keysign
5. HD Keygen

**Comment by Toledit** [comment]
Here are the screenshots required. 
I have found that 800x500 resolution is not that crisp for texts especially. Let me know if I should Up Res them. Granted when upscaled, the size will increase which slow down page load time. 

**CodeArkive**
![screenshotsArtboard 1](https://user-images.githubusercontent.com/27518021/137040944-8fd15b52-33cd-4fc6-a806-2ad647e7270a.jpg)
![screenshotsArtboard 1 copy](https://user-images.githubusercontent.com/27518021/137040958-079507a2-ebde-40de-93a0-03731c867643.jpg)
![screenshotsArtboard 1 copy 2](https://user-images.githubusercontent.com/27518021/137040971-4c0a3500-f17c-45ff-8540-031d345c0fed.jpg)

**Blockchain Explorer**
![screenshotsArtboard 1 copy 3](https://user-images.githubusercontent.com/27518021/137041096-c37bee10-f591-4405-95f5-a24a51c491a7.jpg)
![screenshotsArtboard 1 copy 5](https://user-images.githubusercontent.com/27518021/137041109-9e3be438-fc3d-4b47-bd70-724cf6364e83.jpg)
![screenshotsArtboard 1 copy 4](https://user-images.githubusercontent.com/27518021/137041145-67f47888-f07a-4211-8ab8-5cfedba4bc86.jpg)
![screenshotsArtboard 1 copy 6](https://user-images.githubusercontent.com/27518021/137041157-2b9f54f3-cd63-417d-8690-b8ac2843abe7.jpg)

**TNB Discord Bot**
![screenshotsArtboard 1 copy 9](https://user-images.githubusercontent.com/27518021/137041189-f81c705e-bec1-408c-91a4-c7811cf24fc4.jpg)
![screenshotsArtboard 1 copy 7](https://user-images.githubusercontent.com/27518021/137041196-b476831c-c612-4fcf-bfa1-b3bf4312c6bd.jpg)
![screenshotsArtboard 1 copy 8](https://user-images.githubusercontent.com/27518021/137041199-1489ffda-63b0-47f5-8d2b-49a808d41f06.jpg)

**Keysign**
![screenshotsArtboard 1 copy 12](https://user-images.githubusercontent.com/27518021/137041246-7cddd5bb-a13e-4c03-8f47-db6ddea87b76.jpg)
![screenshotsArtboard 1 copy 13](https://user-images.githubusercontent.com/27518021/137041264-612cc6f1-a3cd-4229-9561-49b8016f204b.jpg)
![screenshotsArtboard 1 copy 14](https://user-images.githubusercontent.com/27518021/137041272-15302840-360b-4f09-b2bd-81848e948f67.jpg)
![screenshotsArtboard 1 copy 15](https://user-images.githubusercontent.com/27518021/137041284-660de931-b6d3-4ef9-b057-a535186fa69f.jpg)

**HD Keygen**
![screenshotsArtboard 1 copy 10](https://user-images.githubusercontent.com/27518021/137041428-b19bb436-82c9-4aac-8326-1ca5065d8b34.jpg)
![screenshotsArtboard 1 copy 11](https://user-images.githubusercontent.com/27518021/137041443-3f371af0-81ca-41b4-a840-8df7d3102a6e.jpg)

**Comment by Toledit** [comment]
**Maakay Discord Bot**
![Artboard 1 copy 17](https://user-images.githubusercontent.com/27518021/137129682-0edf9cbb-0dfe-4dae-8863-37b915ac1053.jpg)
![Artboard 1 copy 16](https://user-images.githubusercontent.com/27518021/137129711-0c02f35a-46b5-4c0f-ac78-e74859caaa74.jpg)
![Artboard 1 copy 18](https://user-images.githubusercontent.com/27518021/137129730-093f2029-8d75-4f61-a581-34988cc3f2ba.jpg)

**Comment by Toledit** [comment]
**Maakay featured cover**
![maakay](https://user-images.githubusercontent.com/27518021/137136402-800cea06-f7bb-4774-b0fc-fd7860551b5c.jpg)

**Comment by kristykjlee** [comment]
@Toledit Hey toledit, can you create app screenshots for TNB Pay & TNB Games? Daniel mentioned he prefer the design team does it instead.

**Comment by Toledit** [comment]
**TNBpay**
![Artboard 1 copy 24](https://user-images.githubusercontent.com/27518021/137225390-e21ff08b-d04e-41eb-998a-3ef0909b561d.jpg)
![Artboard 1 copy 23](https://user-images.githubusercontent.com/27518021/137225404-4f958dd5-3acd-4be0-b95a-4b650fcc2c34.jpg)
![Artboard 1 copy 25](https://user-images.githubusercontent.com/27518021/137225451-1f0a572d-3954-4a46-9e78-ea713206d991.jpg)

**TNB Games**
![Artboard 1 copy 19](https://user-images.githubusercontent.com/27518021/137225516-54e632ac-6b6e-4f63-8b5b-5a574f5522da.jpg)
![Artboard 1 copy 21](https://user-images.githubusercontent.com/27518021/137225547-8cfeee82-5ab9-4933-90bb-3637de1bfd2d.jpg)
![Artboard 1 copy 20](https://user-images.githubusercontent.com/27518021/137225557-aec49815-a008-4072-bcd9-ac509f0d1e06.jpg)
![Artboard 1 copy 22](https://user-images.githubusercontent.com/27518021/137225571-9b3e3a65-5fb1-4ddd-8bdc-2ed5ca94adda.jpg)

**Comment by Toledit** [comment]
**TNB FAUCET**
![Artboard 1 copy 26](https://user-images.githubusercontent.com/27518021/138390761-c4c0f55f-21c5-4767-8a81-1591861d8dc6.jpg)
![Artboard 1 copy 27](https://user-images.githubusercontent.com/27518021/138390767-90fcba4b-21f7-4a74-bc64-e8f1586fe133.jpg)
