### ISSUE TITLE
Social media banner for linkedin & facebook

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#242]
Please create a new social media banner for our linkedin & facebook page. We can use that single design for both platforms.

Just for reference, this is our new website, if you need to use it for inspiration when concepting.
https://www.figma.com/file/Vq4Psr36MFahkgLcqFTNxl/V4-Home-Page?node-id=446%3A2450

**Comment by Toledit** [comment]
Choose one of these 3 and I'll create the same design but for Facebook as Facebook's cover picture **size** differ from LinkedIn.
![Artboard 1 copy 2](https://user-images.githubusercontent.com/27518021/137605258-00564c8b-d0d9-4610-8b55-a386273a17d6.jpg)
![Artboard 1 copy](https://user-images.githubusercontent.com/27518021/137605261-e63c4690-233b-42ce-b75b-b0d05d70b966.jpg)
![Artboard 1](https://user-images.githubusercontent.com/27518021/137605262-87604b53-2ad4-440c-9930-2fd54e9fe9f5.jpg)
Facebook size 851x315
![Facebook](https://user-images.githubusercontent.com/27518021/137605423-d07faf32-a1da-45f2-be20-081cfb4a9b56.jpg)

**Comment by Toledit** [comment]
Let me know if any of these work? or need modification
![Artboard 1 copy 2@2x-100](https://user-images.githubusercontent.com/27518021/137821105-d4bb214a-9d32-47b9-aed7-d6232d3fdf96.jpg)
![Artboard 1 copy 3@2x-100](https://user-images.githubusercontent.com/27518021/137821107-169034fc-bbe4-4273-a4cb-aea36a5f12a0.jpg)
![2](https://user-images.githubusercontent.com/27518021/137821121-e7fb0c26-2b9a-4096-9032-e243b005cc1d.jpg)
![1](https://user-images.githubusercontent.com/27518021/137821132-12f117c9-4229-4062-ad1f-7f3c52d305ef.jpg)
![1 1](https://user-images.githubusercontent.com/27518021/137821135-53257d6c-c01d-4ef4-af4c-781dccc866b5.jpg)

**Comment by Toledit** [comment]
Final Attempt
![Untitled-1](https://user-images.githubusercontent.com/27518021/138422708-a14b7f5d-afa0-4eb9-a0a6-5fcb802ad9e8.jpg)
