### ISSUE TITLE
App Detail Page Links

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Design-Only#243]
**Background**
When users visit an app details page (such as [this one](https://thenewboston.com/arcade/845f0115-d5b4-4d07-b2ac-e4325134254d)) we should also provide links to any additional resources or social medias related to that app.

**Task**
Design an area on the app details page where we can display one or more of the following links related to each app:
- Website (the apps main website)
- Google Play
- Apple App Store
- Discord
- YouTube
- GitHub
- Reddit
- Facebook
- Twitter
- Instagram
- Twitch
- Pinterest
- LinkedIn

**Comment by kashikushi** [comment]
Social media icons added
https://www.figma.com/file/zbQ5xuZqAfhAlOiy9ilZlm/App-Store?node-id=1293%3A10049
