### ISSUE TITLE
Bitty - App page marketing assets

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#249]

**Comment by Toledit** [comment]
**Featured images for Bitty**
![Bitty2](https://user-images.githubusercontent.com/27518021/144728886-5c5dfa0b-a67b-43c2-a5f9-a4e2d20761a2.jpg)
**Screenshots for Bitty on app store**
![Artboard 1 copy 28](https://user-images.githubusercontent.com/27518021/144728776-3a4a93db-430e-4474-8a88-951802092b16.jpg)
![Artboard 1 copy 28-3](https://user-images.githubusercontent.com/27518021/144728775-586dd0b7-c6fd-45df-8e4a-83e17d0d17bc.jpg)
![Artboard 1 copy 28-2](https://user-images.githubusercontent.com/27518021/144728774-3c1a7276-a800-4a7c-9e0a-e042c32aaa46.jpg)
