### ISSUE TITLE
App store product details page design

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Design-Only#251]
Please redesign App store product details based off the improvements you have suggested. 
https://docs.google.com/document/d/1l4VSyZhCJPiC9ycSCprMITqBQrpySCvrO0_qbwuVdmo/edit#heading=h.ofl28civ8cfb

**Comment by osaroadade** [comment]
Hey @kristykjlee does this task card include the wireframe or the entire design from wireframes to hifi?

**Comment by kristykjlee** [comment]
@osaroadade Hey! This includes wireframe to hifi.

**Comment by osaroadade** [comment]
Okay, I just needed clarity on that, Thanks!
